project:
  type: website
  output-dir: public

website:
  title: "Matej Olexa - Blog"
  navbar:
    left:
      - href: /
        text: Home
      - href: /blogs/
        text: Blog
    right:
      - icon: github
        href: https://github.com/olexamatej
      - icon: linkedin
        href: https://www.linkedin.com/in/matej-olexa

lang: en

format:
  html:
    theme: 
      dark: [darkly, assets/css/custom.scss]
    css: 
      - assets/css/custom.scss
    toc: false
    smooth-scroll: true
    page-layout: full
